// <auto-generated />
namespace HandyContextTest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class userimplementhy_entity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userimplementhy_entity));
        
        string IMigrationMetadata.Id
        {
            get { return "201704141641096_user-implement-hy_entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
